### PR TITLE
just some code style ideas, hope this helps

### PR DESCRIPTION
**Pull request by flyingmachine**
sorry @plexus , couldn't resist :P

❤️ you

### CODE REVIEW

**Comment by oxalorg** [comment]
Thanks for the PR @flyingmachine but uhm I don't think using keywords while destructuring a map is idiomatic. 🤔 

In my mind it makes sense to keep them as simple names (or variables) as that is how we refer them in the function body. This fits well with how normal let bindings, or functional parameters work.

Would be happy to understand your reasoning behind this. Cheers.

**Comment by plexus** [comment]
@oxalorg I believe our good friend Daniel, is... how you say? Trolling us

https://twitter.com/plexus/status/1483826485009997828

**Comment by plexus** [comment]
Well played, sir :green_heart: :tophat: :pinched_fingers: 

hat_off

**Comment by oxalorg** [comment]
I was seriously re-evaluating my entire understanding of Clojure 🤣

**Comment by plexus** [comment]
@flyingmachine thank you for your willingness to contribute to the Lambda Island open source collection. Please familiarize yourself with our [style guide](https://nextjournal.com/lambdaisland/clojure-style-guide). I'm going to close this as it's not conform to our style norms.

**Pull request closed without merging**
