### PR TITLE
Correct usage documentation of :no-gen

### PR DESCRIPTION
**Pull request by imrekoszo**
Fixes https://github.com/lambdaisland/kaocha/issues/116

### CODE REVIEW

**Comment by plexus** [comment]
I wasn't involved in writing this plugin. @WhittlesJr does this look good?

That said I think we should replace `:no-gen` with `:kaocha/no-gen`. This makes it clear to a person reading the code that this is kaocha-related metadata, and means we don't clash with other tools.

**Comment by WhittlesJr** [comment]
I believe this is an appropriate change. I probably didn't realize the distinction because I never write my fdefs separately from my functions. (I use `defn-spec` from orchestra.) I also agree that :kaocha/no-gen is a good default value for `:kaocha.filter/skip-meta`.

**Comment by plexus** [comment]
Thanks a lot @imrekoszo

**Comment by imrekoszo** [comment]
Any time, and thanks for this great piece of sw!

**Pull request merged**
