### PR TITLE
Add "canary" tests.

### PR DESCRIPTION
**Pull request by alysbrooks**
Run tests in various repositories using the latest Kaocha. 

Addresses #291 and #301.

### CODE REVIEW

**Comment by alysbrooks** [comment]
If we want it to run only on certain labels we can add the following:

`if: contains(github.event.pull_request.labels.*.name, 'needs-canary-run')`

**Comment by alysbrooks** [comment]
Credit where credit is due: The original idea came from the Rust project (their crater tool) and `rewrite-clj` (the canary tests).

**Comment by humorless** [comment]
Looks good to me.

**Comment by alysbrooks** [comment]
Thanks! @humorless

**Comment by alysbrooks** [comment]
Released in [v1.84.1335](https://github.com/lambdaisland/kaocha/releases/tag/v1.84.1335)

```clj
[lambdaisland/kaocha "1.84.1335"]                 ;; deps.edn
{lambdaisland/kaocha {:mvn/version "1.84.1335"}}  ;; project.clj
```

**Pull request merged**
