### PR TITLE
Add spec validation for the list of plugins.

### PR DESCRIPTION
**Pull request by alysbrooks**
Addresses #36 using @plexus's suggested solution of adding a spec validation check early on.

I added a simple exception handler to just print the exception name and spec failed message, so it looks like the following:

```
java.lang.AssertionError: -- Spec failed --------------------

  {:kaocha/bindings ...,
   :kaocha/tests ...,
   :kaocha/fail-fast? ...,
   :kaocha/color? ...,
   :clojure.spec.test.check/instrument? ...,
   :kaocha/plugins
   [... ... ... kaocha.plugin.alpha/info ... ... ... ... ...],
                ^^^^^^^^^^^^^^^^^^^^^^^^
   :kaocha/reporter ...,
   :clojure.spec.test.check/check-asserts? ...,
   :kaocha.hooks/pre-load ...}

should satisfy

  keyword?

-- Relevant specs -------

:kaocha/plugins:
  (clojure.spec.alpha/coll-of clojure.core/keyword?)
:kaocha/config:
  (clojure.spec.alpha/keys :req ~(conj global-opts :kaocha/tests))

-------------------------
Detected 1 error
```

It looks like Kaocha code base uses `(throw+ {:kaocha/early-exit 0})` in this circumstance, although I'm not sure if the error code is the one we want.

### CODE REVIEW

**Comment by plexus** [comment]
> `(throw+ {:kaocha/early-exit 0})`

This is the process exit code, since this is a non-successful exit it should be non-zero. So far it seems we're using `254` and `253` already, so maybe `252`. It would also be a good idea to document these, so you can check them for instance in a shell script that calls kaocha.

**Comment by alysbrooks** [comment]
I updated it to use a nonzero error code and tweaked the error message a little:

```
ERROR: Invalid configuration file:
-- Spec failed --------------------

  {:kaocha/bindings ...,
   :kaocha/tests ...,
   :kaocha/fail-fast? ...,
   :kaocha/color? ...,
   :clojure.spec.test.check/instrument? ...,
   :kaocha/plugins
   [... ... ... kaocha.plugin.alpha/info ... ... ... ... ...],
                ^^^^^^^^^^^^^^^^^^^^^^^^
   :kaocha/reporter ...,
   :clojure.spec.test.check/check-asserts? ...,
   :kaocha.hooks/pre-load ...}

should satisfy

  keyword?

-- Relevant specs -------

:kaocha/plugins:
  (clojure.spec.alpha/coll-of clojure.core/keyword?)
:kaocha/config:
  (clojure.spec.alpha/keys :req ~(conj global-opts :kaocha/tests))

-------------------------
Detected 1 error
```

(Error will actually appear in red in terminals configured to display color.)

**Comment by plexus** [comment]
Great! In the future please add an entry to the `CHANGELOG.md`. We should probably add a PR template that mentions that, since I'm constantly reminding people :)

**Comment by plexus** [comment]
This has been released in `lambdaisland/kaocha "1.0.732"`.

**Pull request merged**
