### PR TITLE
Provide a warning when no tests are found.

### LINKED ISSUE #34: Provide a warning when no tests are found
This usually has to do with not configuring `test-paths` or `ns-patterns` correctly, and so the warning should hint at that.

### PR DESCRIPTION
**Pull request by dharrigan**
Fixes #34

-=david=-

### CODE REVIEW

**Comment by alysbrooks** [comment]
Overall, looks good.

Can you rebase this?

I'm not sure what the best way forward on the broken test is, as it is already broken (#190). I would suggest borrowing code from `watch-test` so it has at least one test. In any case, I don't think you need to wrap `try+` in another `try`.

**Comment by dharrigan** [comment]
Hi,

Thank you for your kind feedback. I've rebased my branch against master, all is up-to-date. I've removed the usage of the `try+` being wrapped with a `try` (although, it does exist in one other place, namelyy `test/unit/kaocha/report_test.clj`.

Waiting on some feedback from #190 to decide upon what to do with the watch test :-)

**Comment by dharrigan** [comment]
Updated ;)

**Comment by alysbrooks** [comment]
Thanks! Can you add a CHANGELOG entry for this fix? Also, it looks like you added extra lines to `/report_test.clj`

**Comment by alysbrooks** [comment]
Thanks! 
giphy

**Comment by dharrigan** [comment]
You're most welcome! Maybe I can do more! :)

**Comment by alysbrooks** [comment]
That'd be great! Let me know if you have any questions!

**Pull request merged**
