### PR TITLE
Warn when the user has no config

### PR DESCRIPTION
**Pull request by alysbrooks**
If we change the defaults and create a new reader literal for them, `#kaocha/v2`, people with a tests.edn will be fine—they're either using a completely custom config or they're loading a set of defaults they're happy with using `#kaocha/v1`. However, people not using a configuration file at all might see changes in behavior.

To help avoid this, we should warn users when they don't have a configuration file.

```
WARNING: Did not load a configuration file and using the defaults.
This is fine for experimenting, but for long-term use, we recommend creating a configuration file to avoid changes in behavior between releases.
To create a configuration file using the current defaults, create a file named tests.edn that contains 'kaocha/v1 {}'.
```

### CODE REVIEW

**Comment by plexus** [comment]
Looks good! Just needs a CHANGELOG entry. I was going to say warnings like this should be configurable, but in this case the warning IS configurable, just create a `tests.edn`

**Comment by plexus** [comment]
typo

**Comment by alysbrooks** [comment]
I suppose we could also add a way to say, "yes, I want the latest defaults." A reader literal called `#kaocha/latest`, maybe?

**Comment by alysbrooks** [comment]
Added a `CHANGELOG` entry!

**Comment by plexus** [comment]
puppies

**Pull request merged**
